### PR TITLE
incompleted, unknown item id

### PR DESCRIPTION
**Pull request by chxiisana**

### CODE REVIEW

**Comment by braydenleung-Git** [comment]
I will check the which type of leather armour is it considering I’m not sure wether is it also
Color sensitive

**Comment by chxiisana** [comment]
oh btw im still unable to get the id cause no server is hosted and is literally wasting my time and pinging me for no reason

**Comment by braydenleung-Git** [comment]
he was the pateron donator which now cost him much , bla bla bla etc etc . recommend to delete the comment *
also use server using yr pc resource to get the id

**Comment by chxiisana** [comment]
sure, gonna close this pull request but maybe ill reopen it later

**Pull request closed without merging**
